### ISSUE TITLE
gcloud vTPM EK public key to CRT

### ISSUE THREAD

**Issue by osresearch** [osresearch/safeboot#83]
Since google isn't using a CA to sign their vTPM endorsement keys, it is necessary to retrieve them out-of-band and self-sign them. The EK for the vTPM of a google cloud compute engine instance can be extracted https://cloud.google.com/security/shielded-cloud/retrieving-endorsement-key

```
gcloud compute instances get-shielded-identity unified-test
```

This outputs a public key in text format. It should match the key generated with
```
sudo tpm2 createek -c ek.ctx -G rsa -f pem -u ek.pem
```

**Comment by osresearch** [comment]
However, [generating the CSR requires signing it with the EK private key](https://en.wikipedia.org/wiki/Certificate_signing_request#Structure), which the endorsement key is not allowed to be used for signing (only decryption):

```
# tpm2 createek -c ek.ctx -u ek.pub
# tpm2 print -t TPM2B_PUBLIC ek.pub
....
attributes:
  value: fixedtpm|fixedparent|sensitivedataorigin|adminwithpolicy|restricted|decrypt
  raw: 0x300b2
```

This gist claims to be able to swap out the pubkey for the signing, which might work for us https://gist.github.com/op-ct/e202fc911de22c018effdb3371e8335f
